//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFlightCSVToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightIdentity
    {
        public int Id { get; set; }
        public string ICAO { get; set; }
        public string Callsign { get; set; }
    }
}
