//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFlightCSVToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightPos
    {
        public int Id { get; set; }
        public string TransmissionType { get; set; }
        public string ICAO { get; set; }
        public Nullable<System.DateTime> DateGenerate { get; set; }
        public Nullable<System.DateTime> DateLog { get; set; }
        public string Callsign { get; set; }
        public string Altitude { get; set; }
        public string Speed { get; set; }
        public string Track { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string VerticalRate { get; set; }
        public string Squawk { get; set; }
        public string MessageType { get; set; }
    }
}
